# Generated by Django 2.0.7 on 2018-08-26 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_auto_20180826_1135'),
        ('accounts', '0005_auto_20180813_0221'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='review.Organisation'),
        ),
    ]
