# Generated by Django 2.0.7 on 2018-10-19 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_auto_20180826_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='organisation',
        ),
    ]
